RecipePal/RecipePal/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("", RedirectView.as_view(url='account/login_user')),
    path("admin/", admin.site.urls),
    path("account/", include("account.urls")),
    # Spoonacular api url
    path("api/", include("spoonacular_api.urls")),
    # Password reset links
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'),
         name='password_change'),

    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
         name='password_reset_complete'),
]

# Builds a url that tells Django where static and media files hosted in development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RecipePal/account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path("login_user", views.login_user, name="login_user"),
    path("logout_user", views.logout_user, name="logout_user"),
    path("register_user", views.register_user, name="register_user"),
    path("<user_id>", views.account_view, name="account_view"),
    path("<user_id>/edit", views.edit_account_view, name="edit_account_view"),
]

RecipePal/spoonacular_api/urls.py
from django.urls import path
from . import views

app_name = 'spoonacular_api'
urlpatterns = [
     path("recipe_search", views.recipe_search, name='recipe_search'),
     path('recipe_details/<int:recipe_id>/', views.recipe_details, name='recipe_details'),
]

RecipePal/spoonacular_api/models.py
from django.db import models

# Create your models here.

RecipePal/spoonacular_api/forms.py
from django import forms


class RecipeForm(forms.Form):
    # Fields are required by default
    query = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'class': 'form-control mb-2', 'placeholder': "Enter ingredient(s)", 'autofocus': True}))
    cuisine = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'class': 'form-control mb-2', 'placeholder': "Enter cuisine type(s)"}))
    intolerances = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'class': 'form-control mb-2', 'placeholder': "Enter dietary restriction(s)"}))
    type = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'class': 'form-control mb-2', 'placeholder': "Enter meal type(s)"}))

RecipePal/spoonacular_api/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import RecipeForm
import requests
from django.conf import settings


def recipe_search(request):
    if request.method == 'POST':
        # Get the form data
        form = RecipeForm(request.POST)

        # Check if the form is valid
        if form.is_valid():
            # Get the cleaned data from the form
            query = form.cleaned_data['query']
            cuisine = form.cleaned_data['cuisine']
            intolerances = form.cleaned_data['intolerances']
            type = form.cleaned_data['type']

            # Get API key from settings
            api_key = settings.SPOONACULAR_API_KEY
            # Construct the base URL for the API request
            url = f"https://api.spoonacular.com/recipes/complexSearch?apiKey={api_key}"

            # Construct the URL with search parameters from form
            if query:
                url += f'&query={query}'
            if cuisine:
                url += f'&cuisine={cuisine}'
            if intolerances:
                url += f'&intolerances={intolerances}'
            if type:
                url += f'&type={type}'

            # Specify the number of results per page
            url += '&number=500'

            # Make a GET request to Spoonacular API
            response = requests.get(url)

            # Check if the response is successful
            if response.status_code == 200:
                # Extract recipe data from the response
                recipes = response.json()['results']

                # If no recipes found
                if not recipes:
                    # Return an error message. Redirects to search page
                    messages.error(request, "No recipes for this query. Try again")
                    return redirect("spoonacular_api:recipe_search")

                context = {'recipes': recipes}
                # Render the search results template with recipe data
                return render(request, "spoonacular_api/search_results.html", context)
            else:
                # Return an error message. Redirects to search page
                messages.error(request, "Failed to fetch recipes.")
                return redirect("spoonacular_api:recipe_search")
        else:
            # Form is invalid, return errors and go to search page
            messages.error(request, "Form is invalid.")
            return redirect("spoonacular_api:recipe_search")
    else:
        # If the request is not POST, render the form
        form = RecipeForm()
        return render(request, 'spoonacular_api/recipe_search.html', {'form': form})


def recipe_details(request, recipe_id):
    # Get Spoonacular API key from settings
    api_key = settings.SPOONACULAR_API_KEY

    # Construct the URL for fetching recipe details
    url = f"https://api.spoonacular.com/recipes/{recipe_id}/priceBreakdownWidget.json?apiKey={api_key}"

    # Specify the number of results per page
    url += '&number=500'

    # Make a GET request to the Spoonacular API
    response = requests.get(url)

    # Check if the response is successful
    if response.status_code == 200:
        # Extract detailed information from the response
        details = response.json()["ingredients"]

        # Extract image URL for each ingredient
        for ingredient in details:
            ingredient["image"] = f"https://spoonacular.com/cdn/ingredients_100x100/{ingredient['image']}"

        # Prepare context to pass to the template
        context = {'details': details}

        # Render the recipe details template with the recipe information
        return render(request, 'spoonacular_api/recipe_details.html', context)
    else:
        # If the response is not successful, display an error message and redirect to the recipe search page
        messages.error(request, "Failed to fetch recipe details.")
        return redirect("spoonacular_api:recipe_search")

RecipePal/spoonacular_api/templates/spoonacular_api/recipe_details.html
{% extends 'base.html' %}
{% block title %}Recipe Details{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="text-center">Recipe Details</h1>
        <div class="row justify-content-center">
            <div class="col-md-8">
                {% for ingredient in details %}
                    <div class="card mb-3">
                        <div class="row no-gutters">
                            <div class="col-md-4">
                                <img src="{{ ingredient.image }}" class="card-img" alt="{{ ingredient.name }}">
                            </div>
                            <div class="col-md-8">
                                <div class="card-body">
                                    <h5 class="card-title">{{ ingredient.name }}</h5>
                                    <p class="card-text">Price: {{ ingredient.price }} USD</p>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

RecipePal/spoonacular_api/templates/spoonacular_api/recipe_search.html
{% extends 'base.html' %}
{% block title %}Recipe Search{% endblock %}
{% block content %}
    <!--Load static files-->
    {% load static %}
    <link href="{% static 'main/style.css' %}" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <!-- Webpage content -->
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="card card-signin">
                <div class="card-body">
                    <!-- Recipe form -->
                    <form class="form-signin" method="POST">
                    <h1 class="text-center mb-4">Recipe Search</h1>
                        {% csrf_token %}
                        <!-- Logo image -->
                        <div class="d-flex flex-column pb-3">
                            <img class="img-fluid mx-auto d-block" src="{% static 'images/threeChefIcon.jpeg' %}" alt="Three chef clip art" width="150" height="150">
                        </div>
                        <p style="font-size: small"><i>Note: Separate multiple inputs with commas.<br>
                            Ex: pepper, salt, chicken</i></p>
                        <!-- Ingredient field -->
                        <input type="text" name="query" id="inputIngredient" class="form-control mb-2" placeholder="Enter ingredient(s)" autofocus>

                        <!-- Cuisine field -->
                        <input type="text" name="cuisine" id="inputCuisine" class="form-control mb-2" placeholder="Enter cuisine type(s)">

                        <!-- Diet Restriction field -->
                        <input type="text" name="intolerances" id="inputDietrestriction" class="form-control mb-2" placeholder="Enter dietary restriction(s)">

                        <!-- Confirm password field -->
                        <input type="text" name="type" id="inputMealtype" class="form-control mb-2" placeholder="Enter meal type(s)">

                        <!-- Display form errors -->
                        {% for field in recipe_form %}
                            <p>
                                {% for error in field.errors %}
                                    <p style="color: red">{{ error }}</p>
                                {% endfor %}
                            </p>
                        {% endfor %}
                        {% if recipe_form.non_field_errors %}
                            <div style="color: red">
                                <p>{{ recipe_form.non_field_errors }}</p>
                            </div>
                        {% endif %}

                        <!-- Search button -->
                        <button class="btn btn-lg btn-primary btn-block" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

RecipePal/spoonacular_api/templates/spoonacular_api/search_results.html
{% extends 'base.html' %}
{% block title %}Recipe Search Results{% endblock %}

{% block content %}
    <!-- Load static files -->
    {% load static %}
    <link href="{% static 'main/style.css' %}" rel="stylesheet">

    <div class="container">
        <h1 class="text-center">Recipe Search Results</h1>
        <!-- Recipe cards -->
        <div class="d-flex flex-wrap justify-content-center">
            {% for recipe in recipes %}
                <div class="recipe-card mx-2 mb-4">
                    <a href="{% url 'spoonacular_api:recipe_details' recipe.id %}">
                        <!-- Recipe image -->
                        <img src="{{ recipe.image }}" class="recipe-image" alt="{{ recipe.title }}">
                    </a>
                    <!-- Recipe details -->
                    <div class="recipe-details">
                        <!-- Recipe title -->
                        <h5 class="mt-3 mb-1">{{ recipe.title }}</h5>
                    </div>
                </div>
                <!-- Create a new row after every 5th recipe -->
                {% if forloop.counter|divisibleby:5 and not forloop.last %}
                    <div class="w-100"></div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}