RecipePal/RecipePal/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("", RedirectView.as_view(url='account/login_user')),
    path("admin/", admin.site.urls),
    path("account/", include("account.urls")),
    # Spoonacular api url
    path("api/", include("spoonacular_api.urls")),
    # Password reset links
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'),
         name='password_change'),

    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
         name='password_reset_complete'),
]

# Builds a url that tells Django where static and media files hosted in development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RecipePal/account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path("login_user", views.login_user, name="login_user"),
    path("logout_user", views.logout_user, name="logout_user"),
    path("register_user", views.register_user, name="register_user"),
    path("<user_id>", views.account_view, name="account_view"),
    path("<user_id>/edit", views.edit_account_view, name="edit_account_view"),
]

RecipePal/account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from . models import Account


class RegistrationForm(UserCreationForm):
    # Custom registration form with additional email field
    email = forms.EmailField(max_length=254, help_text='Required. Add a valid email address.')

    class Meta:
        # Define the model and fields for the form
        model = Account
        fields = ('email', 'username', 'password1', 'password2', )

    def clean_email(self):
        # Clean and validate the email field
        email = self.cleaned_data['email'].lower()
        try:
            # Check if the email is already in use
            account = Account.objects.exclude(pk=self.instance.pk).get(email=email)
        except Account.DoesNotExist:
            # If email is unique, return it
            return email
        # If email is not unique, raise a validation error
        raise forms.ValidationError('Email "%s" is already in use.' % email)

    def clean_username(self):
        # Clean and validate the username field
        username = self.cleaned_data['username']
        try:
            # Check if the username is already in use
            account = Account.objects.exclude(pk=self.instance.pk).get(username=username)
        except Account.DoesNotExist:
            # If username is unique, return it
            return username
        # If username is not unique, raise a validation error
        raise forms.ValidationError('Username "%s" is already in use.' % username)


class AccountUpdateForm(forms.ModelForm):
    # Form for updating account details.
    class Meta:
        model = Account
        fields = ('username', 'email', 'profile_image', 'hide_email' )

    def clean_email(self):
        # Check if the provided email is unique.
        email = self.cleaned_data['email'].lower()
        try:
            account = Account.objects.exclude(pk=self.instance.pk).get(email=email)
        except Account.DoesNotExist:
            return email
        raise forms.ValidationError('Email "%s" is already in use.' % account)

    def clean_username(self):
        # Check if the provided username is unique.
        username = self.cleaned_data['username']
        try:
            account = Account.objects.exclude(pk=self.instance.pk).get(username=username)
        except Account.DoesNotExist:
            return username
        raise forms.ValidationError('Username "%s" is already in use.' % username)

    def save(self, commit=True):
        # Save the form data to the Account model.
        account = super(AccountUpdateForm, self).save(commit=False)
        account.username = self.cleaned_data['username']
        account.email = self.cleaned_data['email'].lower()
        account.profile_image = self.cleaned_data['profile_image']
        account.hide_email = self.cleaned_data['hide_email']
        if commit:
            account.save()
        return account

RecipePal/templates/password_reset/password_change.html
{% extends 'base.html' %}
{% block title %}Password Change{% endblock %}
{% block content %}
    <!--load static files-->
    {% load static %}
    <link href="{% static 'main/style.css' %}" rel="stylesheet">
    <!--Password change form -->
    <form id="id_password_change_form" method="POST" class="form-signin">{% csrf_token %}
      <h1 class="h3 mb-3 font-weight-normal">Change password</h1>
        <input name="old_password" class="form-control" placeholder="Old password" type="password" id="id_old_password" required="true">
        <input name="new_password1" class="form-control" placeholder="New password" type="password" id="id_new_password1" required="true">
        <input name="new_password2" class="form-control" placeholder="Confirm password" type="password" id="id_new_password2" required="true">

        <!--Display form errors-->
        {% for field in form %}
          {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
          {% endfor %}
        {% endfor %}

      <button id="id_submit_btn" class="btn btn-lg btn-primary btn-block" type="submit">Update</button>
    </form>
{% endblock %}

RecipePal/templates/password_reset/password_change_done.html
{% extends 'base.html' %}
{% block title %}Password Change{% endblock %}
{% block content %}
    <!--load static files-->
    {% load static %}
    <link href="{% static 'main/style.css' %}" rel="stylesheet">

    <div class="container">
        <div class="d-flex flex-column">
            <p class="m-auto">Your password has been updated.</p>
        </div>
    </div>

{% endblock %}

RecipePal/templates/password_reset/password_reset_complete.html
{% extends 'base.html' %}

{% block title %}Password Reset{% endblock %}
{% block content %}
    <!--load static files-->
    {% load static %}
    <link href="{% static 'main/style.css' %}" rel="stylesheet">

    <div class="container">
        <div class="d-flex flex-column">
            <p class="m-auto">Your password has been reset. You can <a style="text-decoration: none" href="{% url 'account:login_user' %}">login</a> now.</p>
        </div>
    </div>
{% endblock %}

RecipePal/templates/password_reset/password_reset_done.html
{% extends 'base.html' %}
{% block title %}Password Reset{% endblock %}
{% block content %}
    <!--load static files-->
    {% load static %}
    <link href="{% static 'main/style.css' %}" rel="stylesheet">
    <div class="container">
        <div class="d-flex flex-column">
              <p class="m-auto p-2">
                We've emailed you instructions for setting your password, if an account exists with the email you entered.
                You should receive them shortly.
              </p>
              <p class="m-auto p-2">
                If you don't receive an email, please make sure you've entered the email you registered with,
                and check your spam folder.
              </p>
              <p class="m-auto p-2"><a style="text-decoration: none" href="{% url 'account:login_user' %}">Return to login page.</a></p>
        </div>
    </div>
{% endblock %}

RecipePal/templates/password_reset/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your Account {{ user.email }},
click the link below:

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
The Open-Chat Team
{% endautoescape %}

RecipePal/templates/password_reset/password_reset_form.html
{% extends 'base.html' %}

{% block title %}Password Reset{% endblock %}
{% block content %}
    <!--load static files-->
    {% load static %}
    <link href="{% static 'main/style.css' %}" rel="stylesheet">

    <form id="id_password_reset_form" method="POST" class="form-signin">{% csrf_token %}
      <h1 class="h3 mb-3 font-weight-normal">Reset password</h1>
        <input name="email" class="form-control" placeholder="Email address" type="email" id="id_email" required="true" >
      <button id="id_submit_btn" class="btn btn-lg btn-primary btn-block" >Send reset email</button>
    </form>



{% endblock %}