RecipePal/RecipePal/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("", RedirectView.as_view(url='account/login_user')),
    path("admin/", admin.site.urls),
    path("account/", include("account.urls")),
    # Spoonacular api url
    path("api/", include("spoonacular_api.urls")),
    # Password reset links
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'),
         name='password_change'),

    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
         name='password_reset_complete'),
]

# Builds a url that tells Django where static and media files hosted in development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RecipePal/account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path("login_user", views.login_user, name="login_user"),
    path("logout_user", views.logout_user, name="logout_user"),
    path("register_user", views.register_user, name="register_user"),
    path("<user_id>", views.account_view, name="account_view"),
    path("<user_id>/edit", views.edit_account_view, name="edit_account_view"),
]

RecipePal/account/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.core.files.storage import FileSystemStorage
from django.conf import settings
import os


# Custom user manager
class MyAccountManager(BaseUserManager):
    # Function to create a new user
    def create_user(self, email, username, password=None):
        # Validate email and username
        if not email:
            raise ValueError('Users must have an email address.')
        if not username:
            raise ValueError('Users must have a username.')

        # Create new user instance
        user = self.model(
            # make characters lowercase
            email=self.normalize_email(email),
            username=username,
        )

        # Set password and save user
        user.set_password(password)
        user.save(using=self._db)
        return user

    # Function to create a new superuser
    def create_superuser(self, email, username, password):
        # Create new user instance
        user = self.create_user(
            email=self.normalize_email(email),
            password=password,
            username=username,
        )
        # Set user as admin, staff, and superuser
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


# Function to define profile image filepath
def get_profile_image_filepath(self):
    return 'profile_images/' + str(self.pk) + '/profile_image.png'


# Function to define default profile image
def get_default_profile_image():
    return "images/dummy_image.png"


# Custom user model
class Account(AbstractBaseUser):
    # Fields
    email           = models.EmailField(verbose_name="email", max_length=60, unique=True)
    username        = models.CharField(max_length=30, unique=True)
    date_joined     = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login      = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin        = models.BooleanField(default=False)
    is_active       = models.BooleanField(default=True)
    is_staff        = models.BooleanField(default=False)
    is_superuser    = models.BooleanField(default=False)
    profile_image   = models.ImageField(max_length=255, upload_to=get_profile_image_filepath, null=True, blank=True, default=get_default_profile_image)
    hide_email      = models.BooleanField(default=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = MyAccountManager()

    # Default return value when you don't access any fields
    def __str__(self):
        return self.username

    def get_profile_image_filename(self):
        return str(self.profile_image)[str(self.profile_image).index('profile_images/' + str(self.pk) + "/"):]

    # For checking permissions. to keep it simple all admin have ALL permissions
    def has_perm(self, perm, obj=None):
        return self.is_admin

    # Does this user have permission to view this app? (ALWAYS YES FOR SIMPLICITY)
    def has_module_perms(self, app_label):
        return True

RecipePal/account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from . models import Account


class RegistrationForm(UserCreationForm):
    # Custom registration form with additional email field
    email = forms.EmailField(max_length=254, help_text='Required. Add a valid email address.')

    class Meta:
        # Define the model and fields for the form
        model = Account
        fields = ('email', 'username', 'password1', 'password2', )

    def clean_email(self):
        # Clean and validate the email field
        email = self.cleaned_data['email'].lower()
        try:
            # Check if the email is already in use
            account = Account.objects.exclude(pk=self.instance.pk).get(email=email)
        except Account.DoesNotExist:
            # If email is unique, return it
            return email
        # If email is not unique, raise a validation error
        raise forms.ValidationError('Email "%s" is already in use.' % email)

    def clean_username(self):
        # Clean and validate the username field
        username = self.cleaned_data['username']
        try:
            # Check if the username is already in use
            account = Account.objects.exclude(pk=self.instance.pk).get(username=username)
        except Account.DoesNotExist:
            # If username is unique, return it
            return username
        # If username is not unique, raise a validation error
        raise forms.ValidationError('Username "%s" is already in use.' % username)


class AccountUpdateForm(forms.ModelForm):
    # Form for updating account details.
    class Meta:
        model = Account
        fields = ('username', 'email', 'profile_image', 'hide_email' )

    def clean_email(self):
        # Check if the provided email is unique.
        email = self.cleaned_data['email'].lower()
        try:
            account = Account.objects.exclude(pk=self.instance.pk).get(email=email)
        except Account.DoesNotExist:
            return email
        raise forms.ValidationError('Email "%s" is already in use.' % account)

    def clean_username(self):
        # Check if the provided username is unique.
        username = self.cleaned_data['username']
        try:
            account = Account.objects.exclude(pk=self.instance.pk).get(username=username)
        except Account.DoesNotExist:
            return username
        raise forms.ValidationError('Username "%s" is already in use.' % username)

    def save(self, commit=True):
        # Save the form data to the Account model.
        account = super(AccountUpdateForm, self).save(commit=False)
        account.username = self.cleaned_data['username']
        account.email = self.cleaned_data['email'].lower()
        account.profile_image = self.cleaned_data['profile_image']
        account.hide_email = self.cleaned_data['hide_email']
        if commit:
            account.save()
        return account

RecipePal/account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.contrib import messages
from . forms import RegistrationForm, AccountUpdateForm
from django.conf import settings
from . models import Account


def login_user(request):
    context = {}
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        # Verify credentials, check against authentication backend
        # returns user object if credentials are valid
        user = authenticate(request, username=username, password=password)
        if user is not None:
            # Login user
            login(request, user)
            return redirect("spoonacular_api:recipe_search")
        else:
            # Return an 'invalid login' error message. Redirects to login page
            messages.error(request, "Your username or password didn't match. Try again.")
            return redirect("account:login_user")
    else:
        return render(request, 'authentication/login.html', context)


def logout_user(request):
    logout(request)
    messages.info(request, "User logged out.")
    return redirect("account:login_user")


def register_user(request, *args, **kwargs):
    # Check if the user is already authenticated
    user = request.user
    if user.is_authenticated:
        return HttpResponse("You are already authenticated as " + str(user.username) + ".")

    context = {}
    if request.POST:
        # If the request method is POST, process the form data
        form = RegistrationForm(request.POST)
        if form.is_valid():
            # If the form is valid, save the user
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            # Authenticate the user and log them in
            account = authenticate(username=username, password=raw_password)
            login(request, account)
            destination = kwargs.get("next")
            if destination:
                # Redirect to the next URL if provided
                return redirect("destination")
            # Redirect to the search page after successful registration
            return redirect('spoonacular_api:recipe_search')
        else:
            # If the form is not valid, pass the form back to the template with errors
            context['registration_form'] = form
    else:
        # If the request method is not POST, render the empty registration form
        form = RegistrationForm()
        context['registration_form'] = form

    return render(request, 'authentication/register.html', context)


def account_view(request, *args, **kwargs):
    context = {}

    # Get the user_id from kwargs
    user_id = kwargs.get("user_id")

    # Fetch the account object using user_id
    try:
        account = Account.objects.get(pk=user_id)
    except:
        return HttpResponse("User does not exist.")

    # If account exists, set the context variables
    if account:
        context['id'] = account.id
        context['username'] = account.username
        context['email'] = account.email
        context['profile_image'] = account.profile_image.url
        context['hide_email'] = account.hide_email

        # Define template variables
        is_self = True
        is_friend = False
        user = request.user

        # Check if the user is authenticated and not the same as the viewed profile
        if user.is_authenticated and user != account:
            is_self = False
        elif not user.is_authenticated:
            is_self = False

        # Set the template variables to the values
        context['is_self'] = is_self
        context['is_friend'] = is_friend
        context['BASE_URL'] = settings.BASE_URL

        # Render the account.html template with the context
        return render(request, "authentication/account.html", context)


def edit_account_view(request, *args, **kwargs):

    # View for editing the user account details.

    # Redirect to login page if user is not authenticated
    if not request.user.is_authenticated:
        return redirect("account:login_user")

    # Retrieve the user's account
    user_id = kwargs.get("user_id")
    account = Account.objects.get(pk=user_id)

    # Check if the user is trying to edit someone else's profile
    if account.pk != request.user.pk:
        return HttpResponse("You cannot edit someone else's profile.")

    context = {}
    if request.POST:
        # Process the form data
        form = AccountUpdateForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            new_username = form.cleaned_data['username']
            # Redirect to the user's profile page after successful update
            return redirect("account:account_view", user_id=account.pk)
        else:
            # If form is not valid, render the form again with errors
            form = AccountUpdateForm(
                                     initial={
                                         "id": account.pk,
                                         "email": account.email,
                                         "username": account.username,
                                         "profile_image": account.profile_image,
                                         "hide_email": account.hide_email,
                                     }
                                     )
            context['form'] = form
    else:
        # Render the form with initial data
        form = AccountUpdateForm(
            initial={
                "id": account.pk,
                "email": account.email,
                "username": account.username,
                "profile_image": account.profile_image,
                "hide_email": account.hide_email,
            }
        )
        context['form'] = form
    # Setting the max data size of an image
    context['DATA_UPLOAD_MAX_MEMORY_SIZE'] = settings.DATA_UPLOAD_MAX_MEMORY_SIZE
    return render(request, "authentication/edit_account.html", context)

RecipePal/account/templates/authentication/account.html
{% extends 'base.html' %}
{% block title %}Account{% endblock %}
{% block content %}
    <!-- Load static files -->
    {% load static %}
    <link href="{% static 'main/style.css' %}" rel="stylesheet">

    <!--Bootstrap CSS-->
    <div class="container-fluid">

    <h1 class="text-center mb-4">User Profile</h1>
        <div class="d-flex flex-row justify-content-center flex-wrap align-items-start">

            <!-- Profile Card -->
            <div class="card profile-card m-2">
              <div class="card-body">
                <div class="d-flex flex-column justify-content-center p-4">
                    <!-- Profile Image -->
                    <div class="image-container mx-auto mb-4">
                        <img class="d-block border border-dark rounded-circle img-fluid mx-auto profile-image" alt="Profile Image" id="id_profile_image" src="{{profile_image}}">
                    </div>
                    <!-- Email -->
                    <p class="mt-4 mb-1 field-heading">Email</p>
                    {% if is_self %}
                        <!-- If viewing own profile show email-->
                        <h5>{{email}}</h5>
                    {% else %}
                        <!--otherwise hide email-->
                        {% if hide_email %}
                            <h5>**********</h5>
                        {% else %}
                            <h5>{{email}}</h5>
                        {% endif %}
                    {% endif %}
                    <!-- Username -->
                    <p class="mt-4 mb-1 field-heading">Username</p>
                    <h5>{{username}}</h5>

                    <!-- If Auth user is viewing their own profile -->
                    {% if is_self %}
                        <!--Variable included in path, must tell django what userid to use -->
                        <a  class="mt-4 btn btn-primary" href="{% url "account:edit_account_view" user_id=id %}">Update</a>
                        <div class="d-flex flex-column mt-4">
                            <a class="m-auto" style="text-decoration: none" href="{% url 'password_change' %}">Change password</a>
                    </div>
                    {% endif %}
                </div>
              </div>
            </div>
        </div>
    </div>

{% endblock content %}

RecipePal/account/templates/authentication/edit_account.html
{% extends 'base.html' %}
{% block title %}Edit Account{% endblock %}

{% block content %}
    <!-- Load static files -->
    {% load static %}
    <link href="{% static 'main/style.css' %}" rel="stylesheet">
    <div class="container-fluid">
    <h1 class="text-center mb-4">User Profile</h1>
    <div class="row justify-content-center">
        <div class="card profile-card">
            <div class="card-body">
                <!-- Form for editing profile -->
                <div class="d-flex flex-column mx-auto p-4">
                    <!-- Profile image container -->
                    <div class="image-container mx-auto text-center" id="id_image_container">
                        <img class="border border-dark rounded-circle img-fluid profile-image" id="id_profile_image" src="{{form.initial.profile_image.url}}" alt="blank person logo">
                        <div class="middle" id="id_middle_container">
                        </div>
                    </div>
                    <!-- Profile edit form -->
                    <form class="form-signin" method="post">{% csrf_token %}
                        <input class="d-none" type="file" id="id_profile_image_file_selector" name="profile_image_file_selector" onchange="readURL(this)">
                        <!-- Email field -->
                        <h6 class="mt-4 field-heading">Email</h6>
                        <input type="email" name="email" id="id_input_email" class="form-control" placeholder="Email address" required autofocus value={{form.initial.email}}>
                        <!-- Username field -->
                        <h6 class="mt-4 field-heading">Username</h6>
                        <input type="text" name="username" id="id_input_username" class="form-control" placeholder="Username" required value="{{form.initial.username}}">

                        <!-- Display form errors -->
                        {% for field in form %}
                        <p>
                        {% for error in field.errors %}
                        <p style="color: red">{{ error }}</p>
                        {% endfor %}
                        </p>
                        {% endfor %}
                        {% if form.non_field_errors %}
                        <div style="color: red">
                            <p>{{form.non_field_errors}}</p>
                        </div>
                        {% endif %}

                        <!-- Submit button -->
                        <div class="d-flex flex-column mt-4">
                            <button class="mt-4 btn btn-primary flex-grow-1" type="submit">Save</button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

RecipePal/account/templates/authentication/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
    <!--load static files-->
    {% load static %}
    <link href="{% static 'main/style.css' %}" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <!-- Webpage content -->
    <div class="container-fluid">
        <h1 class="text-center mb-4">Recipe Pal</h1>
        <div class="row justify-content-center">
            <div class="card card-signin">
                <div class="card-body">
                    <!-- Login form -->
                    <form class="form-signin" method="POST">
                        {% csrf_token %}
                        <!-- Logo image -->
                        <div class="d-flex flex-column pb-3">
                            <img class="img-fluid mx-auto d-block" src="{% static 'images/threeChefIcon.jpeg' %}" alt="Three chef clip art" width="150" height="150">
                        </div>
                        <!-- Username field -->
                        <input type="text" name="username" id="inputUsername" class="form-control mb-2" placeholder="Username" required autofocus>
                        <!-- Password field -->
                        <input type="password" name="password" id="inputPassword" class="form-control mb-2" placeholder="Password" required>

                        <!-- Display form errors -->
                        {% for field in login_form %}
                            <p>
                                {% for error in field.errors %}
                                    <p style="color: red">{{ error }}</p>
                                {% endfor %}
                            </p>
                        {% endfor %}
                        {% if login_form.non_field_errors %}
                            <div style="color: red">
                                <p>{{login_form.non_field_errors}}</p>
                            </div>
                        {% endif %}

                        <!-- Login button -->
                        <button class="btn btn-lg btn-primary btn-block" type="submit">Log in</button>
                    </form>

                    <!-- Reset password link -->
                    <div class="d-flex flex-column my-4">
                        <a class="m-auto" style="text-decoration: none" href="{% url "password_reset" %}">Reset password</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

RecipePal/account/templates/authentication/register.html
{% extends 'base.html' %}
{% block title %}Register{% endblock %}
{% block content %}
    <!--Load static files-->
    {% load static %}
    <link href="{% static 'main/style.css' %}" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <!-- Webpage content -->
    <div class="container-fluid">
    <h1 class="text-center mb-4">Register</h1>
        <div class="row justify-content-center">
            <div class="card card-signin">
                <div class="card-body">
                    <!-- Registration form -->
                    <form class="form-signin" method="post">
                        {% csrf_token %}
                        <!-- Logo image -->
                        <div class="d-flex flex-column pb-3">
                            <img class="img-fluid mx-auto d-block" src="{% static 'images/threeChefIcon.jpeg' %}" alt="Three chef clip art" width="150" height="150">
                        </div>

                        <!-- Email field -->
                        <input type="email" name="email" id="inputEmail" class="form-control mb-2" placeholder="Email address" required autofocus>

                        <!-- Username field -->
                        <input type="text" name="username" id="inputUsername" class="form-control mb-2" placeholder="Username" required>

                        <!-- Password field -->
                        <input type="password" name="password1" id="inputPassword1" class="form-control" placeholder="Password" required>

                        <!-- Confirm password field -->
                        <input type="password" name="password2" id="inputPassword2" class="form-control mb-2" placeholder="Confirm password" required>

                        <!-- Display form errors -->
                        {% for field in registration_form %}
                            <p>
                                {% for error in field.errors %}
                                    <p style="color: red">{{ error }}</p>
                                {% endfor %}
                            </p>
                        {% endfor %}
                        {% if registration_form.non_field_errors %}
                            <div style="color: red">
                                <p>{{ registration_form.non_field_errors }}</p>
                            </div>
                        {% endif %}

                        <!-- Register button -->
                        <button class="btn btn-lg btn-primary btn-block" type="submit">Register</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}