RecipePal/RecipePal/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("", RedirectView.as_view(url='account/login_user')),
    path("admin/", admin.site.urls),
    path("account/", include("account.urls")),
    # Spoonacular api url
    path("api/", include("spoonacular_api.urls")),
    # Password reset links
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'),
         name='password_change'),

    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
         name='password_reset_complete'),
]

# Builds a url that tells Django where static and media files hosted in development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RecipePal/account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path("login_user", views.login_user, name="login_user"),
    path("logout_user", views.logout_user, name="logout_user"),
    path("register_user", views.register_user, name="register_user"),
    path("<user_id>", views.account_view, name="account_view"),
    path("<user_id>/edit", views.edit_account_view, name="edit_account_view"),
]

RecipePal/spoonacular_api/urls.py
from django.urls import path
from . import views

app_name = 'spoonacular_api'
urlpatterns = [
     path("recipe_search", views.recipe_search, name='recipe_search'),
     path('recipe_details/<int:recipe_id>/', views.recipe_details, name='recipe_details'),
]

RecipePal/templates/snippets/footer.html
<!-- load static files -->
{% load static %}
<link href="{% static 'main/style.css' %}" rel="stylesheet">

<!-- Bootstrap CSS -->
<div class="d-flex flex-row align-items-center footer bg-white shadow-lg mt-4">
    <p class="m-auto">&copy; 2024 | RecipePal | Raymond Lee</p>
</div>

RecipePal/templates/snippets/header.html
<!-- load static files -->
{% load static %}
<link href="{% static 'main/style.css' %}" rel="stylesheet">

<div class="d-flex p-3 px-md-4 mb-4 bg-white border-bottom shadow-sm">
    <!-- Medium to large screen -->
    <div class="d-none d-md-flex flex-row my-auto flex-grow-1 align-items-center">
        <!-- col1 in flex-row-->
        <h5 class="mr-3 font-weight-normal justify-content-start">
            <!--if user is authenticated home button goes to recipe search page, otherwise home is login screen-->
            {% if request.user.is_authenticated %}
                <a class="p-2 text-dark" style="text-decoration: none" href="{% url "spoonacular_api:recipe_search" %}">Home</a>
            {% else %}
                <a class="p-2 text-dark" style="text-decoration: none" href="{% url "account:login_user" %}">Home</a>
            {% endif %}
        </h5>

        <!-- col2 in flex-row-->
        <div class="d-flex flex-row-reverse flex-grow-1">
            <nav>
                <!-- user is logged in-->
                {% if request.user.is_authenticated %}
                    <!-- dropdown button for account and logout-->
                    <div class="btn-group dropstart">
                        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <img class="account-image rounded-circle m-auto d-block" src="{{ request.user.profile_image.url }}" alt="account icon logo" width="22" height="22">
                        </button>
                        <ul class="dropdown-menu dropdown-menu-dark">
                            <!--Variable included in path, must tell django what userid to use -->
                            <li><a class="dropdown-item" href="{% url "account:account_view" user_id=request.user.id %}">Account</a></li>
                            <li><a class="dropdown-item" href="{% url "account:logout_user" %}">Logout</a></li>
                        </ul>
                    </div>

                    <!-- user is logged out-->
                {% else %}
                    <a class="p-2 text-dark" style="text-decoration: none" href="{% url "account:login_user" %}">Login</a>
                    <a class="btn btn-outline-primary" href="{% url "account:register_user" %}">Register</a>
                {% endif %}
            </nav>
        </div>
    </div>

    <!-- Small to medium screen -->
    <div class="d-flex d-md-none flex-column mx-auto align-items-center">
        <!-- row1 in flex-column-->
        <h5 class="font-weight-normal justify-content-start">
            <!--if user is authenticated home button goes to index page, otherwise home is login screen-->
            {% if request.user.is_authenticated %}
                <a class="p-2 text-dark" style="text-decoration: none" href="{% url "spoonacular_api:recipe_search" %}">Home</a>
            {% else %}
                <a class="p-2 text-dark" style="text-decoration: none" href="{% url "account:login_user" %}">Home</a>
            {% endif %}
        </h5>

        <!-- row2 in flex-column-->
        <div class="d-flex flex-row-reverse flex-grow-1">
            <nav>
                <!-- user is logged in-->
                {% if request.user.is_authenticated %}
                    <!-- dropdown button for account and logout-->
                    <div class="btn-group dropstart">
                        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <img class="account-image rounded-circle m-auto d-block" src="{{ request.user.profile_image.url }}" alt="account icon logo" width="22" height="22">
                        </button>
                        <ul class="dropdown-menu dropdown-menu-dark">
                            <!--Variable included in path, must tell django what userid to use -->
                            <li><a class="dropdown-item" href="{% url "account:account_view" user_id=request.user.id %}">Account</a></li>
                            <li><a class="dropdown-item" href="{% url "account:logout_user" %}">Logout</a></li>
                        </ul>
                    </div>

                    <!-- user is logged out-->
                {% else %}
                    <a class="p-2 text-dark" style="text-decoration: none" href="{% url "account:login_user" %}">Login</a>
                    <a class="btn btn-outline-primary" href="{% url "account:register_user" %}">Register</a>
                {% endif %}
            </nav>
        </div>
    </div>


</div>